auto:
  name: ğŸ¤– Avto
  welcome_message: ğŸ¤– Assalomu alaykum, Men <b>Presento AI botman</b>. Nima yaratmoqchisiz?
  parse_mode: html


manual:
  name: ğŸ‘©ğŸ¼â€ğŸ’» Qo'lda
  welcome_message: ğŸ‘©ğŸ¼â€ğŸ’» Nima yaratmoqchisiz?
  parse_mode: html
